### ISSUE TITLE
Incorrect opening and closing state

### ISSUE THREAD

**Issue by anderscheow** [medyas/flutter_zoom_drawer#99] opened 2022-04-29 06:55 UTC
The state return from `ZoomDrawerController.stateNotifier` is incorrect for opening and closing.

When I try to slide to open, the state return is `DrawerState.closing`; whereas slide to close, the state return is `DrawerState.opening`.

FY: `isRtl` = true

**Comment by YDA93** [comment] 2022-04-30 08:49
@anderscheow  When you drag in/out, the state is always opening.

You can use DrawerLastAction if you want to know the last action from drawer whether it was opened or closed.

`context.drawerLastAction`

**Comment by medyas** [comment] 2022-06-01 14:13
@anderscheow could you provide more details about this issue

**Comment by medyas** [comment] 2022-07-15 09:06
@anderscheow after checking, i think its caused by the `AnimationController.fling()` method, as its calling both animation `forward` & `reverse`. I added some checks to try and dismiss the extra unwanted animation status that causing this issue.
You can find this in the latest release. 
will close this, and you can reopen if the problem still exists.

**Closed as completed by medyas** 2022-07-15 09:06 UTC
