### ISSUE TITLE
rotation not working

### ISSUE THREAD

**Issue by shadycyan** [medyas/flutter_zoom_drawer#62] opened 2021-10-23 17:51 UTC
Hi, I recently use your package and face this weird issue that no matter what number I put for angle rotate value (between 0 to -30.0), it's not working...

**Comment by medyas** [comment] 2021-11-02 07:24
@shadycyan sorry for the late response. Will try to check this and get back to you.

**Comment by medyas** [comment] 2021-11-09 15:45
@shadycyan could you provide which style you were using ?

**Comment by huanlirui** [comment] 2021-11-17 10:34
i face same issue

**Comment by medyas** [comment] 2021-11-17 16:44
@huanlirui could you provide which style you were using ?

**Comment by huanlirui** [comment] 2021-11-18 02:14
@medyas  Please look at my code. I don't know which section of code is missing, which leads to this error
![image](https://user-images.githubusercontent.com/40491203/142338903-6f7f4c3d-9ccf-461e-9ff2-7ff968f6e089.png)

**Comment by huanlirui** [comment] 2021-11-19 02:36
help help

**Comment by medyas** [comment] 2021-11-19 14:09
@huanlirui try to replace it with the `call` method.
```dart
drawerController.toggle?.call();
```

**Comment by shadycyan** [comment] 2021-11-22 07:58
I tried drawerController.toggle?.call() now, and it still rotation not working. 



this is my style config:

final _drawerController = ZoomDrawerController();

ZoomDrawer(
          controller: _drawerController,
          menuScreen: const MenuScreen(),
          mainScreen: const MainScreen(),
          isRtl: true,
          borderRadius: 24.0,
          mainScreenScale: 0.15,
          angle: -12.0,
          backgroundColor: Colors.grey[300]!,
          slideWidth: Get.size.width * (0.6),
)

**Comment by medyas** [comment] 2021-11-23 07:46
@shadycyan i just tested the example app and its working, so this is probably an issue with your implemented code.
could you provide a a reproducible sample app with this issue ?

**Comment by JesusHdez960717** [comment] 2021-12-08 16:53
@shadycyan, rotation it's not working because you are using the default styling, if you take a look under the hood, the `renderDefault()` method in `flutter_zoom_drawer` don't take into account the angle, I solve this same issue by using the DrawerStyle.Style1. Here is my ZoomDrawer's config:
```dart
GetBuilder<MyDrawerController>(
      builder: (_) => ZoomDrawer(
        controller: _.zoomDrawerController,//some empty controller
        menuScreen: MenuScreen(),
        mainScreen: MainScreen(),
        borderRadius: 24.0,
        showShadow: true,
        angle: -12.0,
        style: DrawerStyle.Style1,
        backgroundColor: Colors.grey[400]!,
        slideWidth: MediaQuery.of(context).size.width * 0.65,
      ),
    )
```

If need more info on my answer, look at the Issue #67 for a 'complete' simple example.
Hope this help. :+1:

**Comment by multi-net** [comment] 2021-12-14 12:15
I have the the same issue but when changing app locale!
I mean rotation works fine at first, but when I change app Locale and the UI reversed the toggle method doesn't work

**Comment by medyas** [comment] 2021-12-14 12:18
@multi-net could you provide more details & sample code

**Comment by multi-net** [comment] 2021-12-14 12:22
```
import 'package:atc_new/app/view_model_provider/app_language_provider.dart';
import 'package:atc_new/app/view_model_provider/home_provider.dart';
import 'package:atc_new/utils/consts.dart';
import 'package:flutter/material.dart';
import 'package:flutter_zoom_drawer/flutter_zoom_drawer.dart';
import 'package:provider/provider.dart';

import 'drawer/app_drawer.dart';
import 'widgets/home_app_bar.dart';
import 'widgets/home_body.dart';

class HomeView extends StatelessWidget {
  const HomeView({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProxyProvider<AppLanguageProvider, HomeProvider>(
      create: (context) => HomeProvider(context.read<AppLanguageProvider>()),
      update: (context, appLanguageProvider, homeProvider) {
        return HomeProvider(appLanguageProvider);
      },
      builder: (context, child) {
        final provider = context.watch<HomeProvider>();
        return Scaffold(
          body: ZoomDrawer(
            isRtl: provider.rtl(),
            angle: -12.0,
            slideWidth: Consts.width * .50,
            controller: provider.drawerController,
            backgroundColor: Consts.colors.primaryColor,
            openCurve: Curves.fastOutSlowIn,
            borderRadius: 60.0,
            showShadow: true,
            mainScreenScale: .3,
            mainScreen: Container(
              padding: const EdgeInsets.all(24),
              decoration: BoxDecoration(
                color: Consts.colors.accentColor,
                image: DecorationImage(
                    image: AssetImage(
                      Consts.assets.header,
                    ),
                    fit: BoxFit.fitWidth,
                    alignment: Alignment.topCenter),
              ),
              child: Column(
                children: const [
                  HomeAppBar(),
                  HomeBody(),
                ],
              ),
            ),
            menuScreen: const AppDrawer(),
          ),
        );
      },
    );
  }
}

```

**Comment by multi-net** [comment] 2021-12-14 12:23
![image](https://user-images.githubusercontent.com/94140926/145997658-b3f6d4bd-3ed8-456c-bbb5-7dd87a986898.png)

**Comment by multi-net** [comment] 2021-12-14 12:24
when I call this function in the image. the toggle doesn't work

**Comment by multi-net** [comment] 2021-12-14 12:25
my toggle function 
   
![image](https://user-images.githubusercontent.com/94140926/145997914-a9ac445d-fb30-470b-a38b-14e18fa74a5b.png)

**Comment by multi-net** [comment] 2021-12-14 12:29
for more details:
If you noticed, I am using provider. The problem happened when i have just used proxy provider

**Comment by medyas** [comment] 2021-12-14 12:33
so technically this is not related to the package it self. maybe remove the proxy provide and that should fix it.
in here, try updating the HomeProvider instance and not returning a new instance, maybe this will fix it
```dart
update: (context, appLanguageProvider, homeProvider) {
        return HomeProvider(appLanguageProvider);
      },
```

**Comment by multi-net** [comment] 2021-12-14 12:43
awesome!
I just returned the previous `HomeProvider` provider instead of new one.
thanks a lot

**Comment by medyas** [comment] 2021-12-14 12:45
Closing as it turned out its not related to the package it self rather to how its used in apps.

**Closed as completed by medyas** 2021-12-14 12:45 UTC
